language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: q43dGZvPZWaebT667BOdQY5YdefchGewSykfKTp6gNTIxapgRaKASzMD2oIkfHqE9/H9JqqnhrWJpGd6ZXrFO6d8/n3rg7uFpDvGkYYV+I5CD9qcDy4wfvjJAXq1MtZiuXsVdhLnicT+0GwZ5G3OpkJ5qeXQ+mIF6NrYbIUBQNQ=
  app: surrealcomics
  on:
    repo: 8manos/surreal
